name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # The format is: https://[USERNAME]:[TOKEN]@huggingface.co/spaces/[USERNAME]/[SPACE_NAME]
          # We'll use KhoaHoang2 as the default username and Blackjack-ai- as the space name.
        run: git push --force https://KhoaHoang2:$HF_TOKEN@huggingface.co/spaces/KhoaHoang2/Blackjack-ai- main
